version: '3.1'

services:
  esper_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${ESPER_DATABASE_NAME}
      - POSTGRES_USER=${ESPER_DATABASE_USER}
      - POSTGRES_PASSWORD=${ESPER_DATABASE_PASSWORD}
    ports:
      - 5432:5432
  esper:
    image: jvalskis/esper:${IMAGE_ESPER_VERSION}
    restart: always
    ports:
      - 9000:9000
    environment:
      - HASS_WEBSOCKET_URL
      - HASS_ACCESS_TOKEN
      - ESPER_DATABASE_NAME
      - ESPER_DATABASE_USER
      - ESPER_DATABASE_PASSWORD
      - ESPER_DATABASE_URL
      - ESPER_MAIL_SMTP_HOST
      - ESPER_MAIL_SMTP_PORT
      - ESPER_MAIL_SMTP_TLS
      - ESPER_MAIL_SMTP_SSL
      - ESPER_MAIL_SMTP_USERNAME
      - ESPER_MAIL_SMTP_PASSWORD
      - ESPER_MAIL_SMTP_FROM
      - ESPER_MAIL_SMTP_RECIPIENTS
      - ESPER_PORT
      - ESPER_HOST