version: '3.1'

services:
  esper_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/:ro
  esper_app:
    build: .
    restart: always
    ports:
      - 9000:9000
    environment:
      - HASS_WEBSOCKET_URL
      - HASS_ACCESS_TOKEN
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST