version: '3.1'

services:
  esper_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: esper
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/:ro