apiVersion: v2
appVersion: 0.2.0
description: Esper is an IOT device firmware manager
name: esper
version: 3.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - esper
home: https://github.com/jvalskis/esper/tree/master/charts/esper
sources:
  - https://github.com/jvalskis/esper
maintainers:
  - name: jvalskis
    url: https://github.com/jvalskis
dependencies:
  - name: common
    version: 3.3.1
    repository: https://bjw-s.github.io/helm-charts/
  - name: postgresql
    version: 15.5.21
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled