#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
image:
  # -- image repository
  repository: jvalskis/esper-app
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# -- environment variables.
# @default -- See below
env:
  # -- Service hostname
  ESPER_HOST: "localhost"
  # -- Service port
  ESPER_PORT: 80
  # -- Home assistant websocket
  HASS_WEBSOCKET_URL: "ws://homeassistant/api/websocket"
  # -- Home assistant access token
  HASS_ACCESS_TOKEN: "token"
  # -- Postgres user
  ESPER_DATABASE_USER: "esper"
  # -- Postgres password
  ESPER_DATABASE_PASSWORD: "password"
  # -- Postgres database
  ESPER_DATABASE_NAME: "esper"
  # -- Postgres host
  ESPER_DATABASE_SERVER: "esper-postgresql"
  # -- Postgres port
  ESPER_DATABASE_PORT: 5432

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false

# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
postgresql:
  enabled: true
#  auth:
#    postgresPassword: ""
#    username: ""
#    password: ""
#    database: ""
  persistence:
    enabled: true
    storageClass:
    accessModes:
      - ReadWriteOnce