#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
strategy:
  type: Recreate

controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          # -- image repository
          repository: jvalskis/esper
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables.
        # @default -- See below
        env:
          TZ: UTC
          # -- Service hostname
          ESPER_HOST: "0.0.0.0"
          # -- Service port
          ESPER_PORT: 80
          # -- Home assistant websocket
          #  HASS_WEBSOCKET_URL: "ws://homeassistant/api/websocket"
          # -- Home assistant access token
          #  HASS_ACCESS_TOKEN: "token"
          # -- Postgres user
          ESPER_DATABASE_USER: "esper"
          # -- Postgres password
          #  ESPER_DATABASE_PASSWORD: "password"
          # -- Postgres database
          ESPER_DATABASE_NAME: "esper"
          # -- Postgres host
          ESPER_DATABASE_URL: "jdbc:postgresql://db:5432/esper"
          # -- Value in seconds for how long to wait for a Shelly device to flash firmware
          SHELLY_FIRMWARE_FLASH_TIMEOUT: 20
          # -- SMTP host
          #  ESPER_MAIL_SMTP_HOST:
          # -- SMTP port
          #  ESPER_MAIL_SMTP_PORT:
          # -- SMTP tls enabled
          #  ESPER_MAIL_SMTP_TLS: false
          # -- SMTP ssl enabled
          #  ESPER_MAIL_SMTP_SSL: false
          # -- SMTP username
          #  ESPER_MAIL_SMTP_USERNAME:
          # -- SMTP password
          #  ESPER_MAIL_SMTP_PASSWORD:
          # -- Address to send the notifications from
          #  ESPER_MAIL_SMTP_FROM:
          # -- Notification recipients, comma separated
          #  ESPER_MAIL_SMTP_RECIPIENTS:

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false

# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
postgresql:
  enabled: true